### ISSUE TITLE
What is the expected accuracy on CUB?

### ISSUE THREAD

**Issue by D-X-Y** [Fezaries/CRnet#1]
Hi, thanks for this code.
I directly download the codes and run `CUDA_VISIBLE_DEVICES=7 python CUB_train.py`.
I obtain `seen=0.5804, unseen=0.4108, h=0.4811` finally, is it ok?
If I want to run AWA2, which parameters should I change?
Best Regards,

**Comment by Fezaries** [comment]
Hi, Dong, thank you for your attention to this work.

There was a minor error in the previous code (row 102 `att = np.unique(att,axis=0)` was missing), I must say sorry for this. And now it has been corrected.

But it seems that the impact of the error is not big, and the accuracy you obtained is within an acceptable range.

I retrained twice with the new code and uploaded the models and logs, you can have a look. And I also updated the code for AwA2.
[(CUB)2019-08-06 16:46:16.log](https://github.com/Fezaries/CRnet/files/3472185/CUB.2019-08-06.16.46.16.log)
[(CUB)2019-08-06 16:24:52.log](https://github.com/Fezaries/CRnet/files/3472187/CUB.2019-08-06.16.24.52.log)

It should be pointed out that due to the randomness of the initialization algorithm and sampling algorithm, the results will slightly fluctuate. Thus I believe the algorithm has room for further improvement.

**Comment by D-X-Y** [comment]
Thanks for your answers!
